// Navigation config for every "Screen recording" slide in the storyboard.
// menuPath: array of visible text labels to click in order (top nav → submenu)
// actions: Playwright steps after landing on the screen
//   { type: 'click', text: 'visible text' }
//   { type: 'fill', selector: 'css selector', value: 'text to type' }
//   { type: 'wait', ms: number }
//   { type: 'hover', text: 'visible text' }
// duration: total recording time in ms (after actions complete)

module.exports = [

  // ── Manage Job ──────────────────────────────────────────────────────────────
  {
    module: 'manage_job',
    slide: 3,
    label: 'Add New Job',
    menuPath: ['Records', 'Manage Job'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'click', text: 'Add New' },
      { type: 'wait', ms: 800 },
      { type: 'fill', selector: 'input[name*="job"], input[placeholder*="Job Name"], input[placeholder*="name"]', value: 'Demo Event 2026' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Save' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 12000,
  },
  {
    module: 'manage_job',
    slide: 4,
    label: 'Add Shift and Role',
    menuPath: ['Records', 'Manage Job'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Shifts' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Add New' },
      { type: 'wait', ms: 600 },
      { type: 'fill', selector: 'input[placeholder*="shift"], input[placeholder*="Shift"]', value: 'Morning Shift' },
      { type: 'wait', ms: 500 },
      { type: 'click', text: 'Add Role' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Save' },
      { type: 'wait', ms: 1200 },
    ],
    duration: 14000,
  },
  {
    module: 'manage_job',
    slide: 5,
    label: 'Copy Job',
    menuPath: ['Records', 'Manage Job'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'click', selector: '[title*="Copy"], [class*="copy"], img[alt*="copy"]' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Daily' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Copy' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 12000,
  },

  // ── MSS ─────────────────────────────────────────────────────────────────────
  {
    module: 'mss',
    slide: 3,
    label: 'Manager Portal - Event List',
    menuPath: ['Tools', 'Manager Portal'],
    actions: [
      { type: 'wait', ms: 2000 },
      { type: 'hover', text: 'Variance' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 10000,
  },
  {
    module: 'mss',
    slide: 4,
    label: 'Web Shift Tab',
    menuPath: ['Tools', 'Manager Portal'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Web Shift' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Add to Web Shift' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 12000,
  },
  {
    module: 'mss',
    slide: 6,
    label: 'Web Shift Approval',
    menuPath: ['Tools', 'Manager Portal'],
    actions: [
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Web Shift Approval' },
      { type: 'wait', ms: 1200 },
      { type: 'hover', text: 'Approve' },
      { type: 'wait', ms: 800 },
      { type: 'hover', text: 'Deny' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 12000,
  },

  // ── Scheduling ──────────────────────────────────────────────────────────────
  {
    module: 'scheduling',
    slide: 3,
    label: 'Schedule by Employee',
    menuPath: ['Scheduling', 'Schedule by Employee'],
    actions: [
      { type: 'wait', ms: 1500 },
      { type: 'fill', selector: 'input[placeholder*="employee"], input[placeholder*="Employee"], input[placeholder*="search"], input[placeholder*="Search"]', value: 'Smith' },
      { type: 'wait', ms: 800 },
      { type: 'click', selector: 'input[placeholder*="Search"] + button, button[title*="Search"], button:has-text("Search")' },
      { type: 'wait', ms: 1200 },
      { type: 'click', selector: 'td:has-text("Smith"), a:has-text("Smith")' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: '[class*="checkmark"], [class*="green"], button[title*="Save"]' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 16000,
  },
  {
    module: 'scheduling',
    slide: 4,
    label: 'Schedule by Job',
    menuPath: ['Scheduling', 'Schedule by Job'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'input[placeholder*="job"], input[placeholder*="Job"], input[placeholder*="number"]', value: '12345' },
      { type: 'wait', ms: 600 },
      { type: 'click', selector: 'input[type="checkbox"]' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1200 },
      { type: 'click', text: 'Save' },
      { type: 'wait', ms: 1200 },
    ],
    duration: 14000,
  },

  // ── Schedule by Job Admin ────────────────────────────────────────────────────
  {
    module: 'schedule_by_job_admin',
    slide: 4,
    label: 'Schedule by Job Admin',
    menuPath: ['Scheduling', 'Schedule by Job Admin'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'input[placeholder*="job"], input[placeholder*="Job"]', value: '12345' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1200 },
      { type: 'click', selector: 'input[type="checkbox"]' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Save' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 14000,
  },

  // ── General Reporting ────────────────────────────────────────────────────────
  {
    module: 'general_reporting',
    slide: 3,
    label: 'Job Administration Reports',
    menuPath: ['Reports', 'Job Administration'],
    actions: [
      { type: 'wait', ms: 2000 },
      { type: 'hover', selector: 'ul li, .report-list li, td a' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 10000,
  },

  // ── Payroll Reporting ────────────────────────────────────────────────────────
  {
    module: 'payroll_reporting',
    slide: 3,
    label: 'Payroll Reports',
    menuPath: ['Reports'],
    actions: [
      { type: 'wait', ms: 1500 },
      { type: 'hover', text: 'Payroll' },
      { type: 'wait', ms: 1200 },
    ],
    duration: 10000,
  },

  // ── Admin Reporting ──────────────────────────────────────────────────────────
  {
    module: 'admin_reporting',
    slide: 3,
    label: 'All Report Categories',
    menuPath: ['Reports'],
    actions: [
      { type: 'wait', ms: 2000 },
    ],
    duration: 10000,
  },

  // ── Workforce Scheduler Maintenance ─────────────────────────────────────────
  {
    module: 'workforce_scheduler_mntnnce',
    slide: 3,
    label: 'Manage Employee Tabs',
    menuPath: ['Records', 'Manage Employee'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'fill', selector: 'input[placeholder*="last"], input[placeholder*="Last"], input[placeholder*="Search"]', value: 'Gonzalez' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'a[href*="employee"], td a' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Personal Info' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Licensing' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Background Check' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Employee Notes' },
      { type: 'wait', ms: 800 },
    ],
    duration: 18000,
  },

  // ── Workforce Admin Maintenance ──────────────────────────────────────────────
  {
    module: 'workforce_admin_maintenance',
    slide: 3,
    label: 'Disciplinary Action, Pay Rate, Training tabs',
    menuPath: ['Records', 'Manage Employee'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'fill', selector: 'input[placeholder*="last"], input[placeholder*="Search"]', value: 'Gonzalez' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'a[href*="employee"], td a' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Disciplinary Action' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Pay Rate' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Training' },
      { type: 'wait', ms: 800 },
    ],
    duration: 16000,
  },

  // ── Employee HR Record Maintenance ───────────────────────────────────────────
  {
    module: 'employee_hr_record_maintenance',
    slide: 3,
    label: 'All Employee Tabs',
    menuPath: ['Records', 'Manage Employee'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'fill', selector: 'input[placeholder*="last"], input[placeholder*="Search"]', value: 'Gonzalez' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'a[href*="employee"], td a' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Status' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Email' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Phone' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Pay Rate' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Background Check' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Exclusions' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Tasks' },
      { type: 'wait', ms: 800 },
    ],
    duration: 20000,
  },
  {
    module: 'employee_hr_record_maintenance',
    slide: 4,
    label: 'Employee Status Search',
    menuPath: ['Records', 'Manage Employee'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Status' },
      { type: 'wait', ms: 800 },
      { type: 'fill', selector: 'select[name*="branch"], select[name*="Branch"]', value: '1' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1200 },
      { type: 'hover', text: 'Pending' },
      { type: 'wait', ms: 800 },
    ],
    duration: 14000,
  },

  // ── Hiring Manager ───────────────────────────────────────────────────────────
  {
    module: 'hiring_manager',
    slide: 3,
    label: 'Import from Hiring Portal',
    menuPath: ['Tools', 'Import from Hiring Portal'],
    actions: [
      { type: 'wait', ms: 1500 },
      { type: 'hover', text: 'Background Status' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'input[type="radio"], input[type="checkbox"]' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Import Applicant' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 14000,
  },

  // ── Hiring Admin ─────────────────────────────────────────────────────────────
  {
    module: 'hiring_admin',
    slide: 3,
    label: 'Tasks Tab',
    menuPath: ['Records', 'Manage Employee'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'fill', selector: 'input[placeholder*="Search"]', value: 'Gonzalez' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'a[href*="employee"], td a' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Tasks' },
      { type: 'wait', ms: 1000 },
      { type: 'hover', selector: 'td:has-text("Pending"), tr:has-text("pending")' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 14000,
  },

  // ── Mail By ──────────────────────────────────────────────────────────────────
  {
    module: 'mail_by',
    slide: 3,
    label: 'Mail By Employee and Job',
    menuPath: ['Scheduling'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'hover', text: 'Mail By Employee' },
      { type: 'wait', ms: 1000 },
      { type: 'hover', text: 'Mail By Job' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Mail By Employee' },
      { type: 'wait', ms: 1200 },
    ],
    duration: 14000,
  },

  // ── Sign-In / Sign-Out ───────────────────────────────────────────────────────
  {
    module: 'sign_in_sign_out',
    slide: 3,
    label: 'Sign-In Config',
    menuPath: ['Time Clock', 'Sign-In Config'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'select[name*="event"], select[name*="Event"]', value: '1' },
      { type: 'wait', ms: 600 },
      { type: 'fill', selector: 'select[name*="venue"], select[name*="Venue"]', value: '1' },
      { type: 'wait', ms: 600 },
      { type: 'fill', selector: 'select[name*="job"], select[name*="Job"]', value: '1' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Add to Shift List' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Go to Sign-In' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 16000,
  },
  {
    module: 'sign_in_sign_out',
    slide: 4,
    label: 'Sign-In Screen',
    menuPath: ['Time Clock', 'Sign-In Config'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'click', text: 'Go to Sign-In' },
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'input[placeholder*="ID"], input[placeholder*="id"], input[placeholder*="scan"]', value: '123456' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Pause' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Correction' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'OK' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 16000,
  },
  {
    module: 'sign_in_sign_out',
    slide: 5,
    label: 'Sign-Out Config',
    menuPath: ['Time Clock', 'Sign-In/Sign-Out Config'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'click', text: 'Sign-Out' },
      { type: 'wait', ms: 1000 },
      { type: 'hover', text: '2' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 12000,
  },

  // ── Manual Process Hours ─────────────────────────────────────────────────────
  {
    module: 'manual_process_hours',
    slide: 3,
    label: 'Manage Process Hours',
    menuPath: ['Payroll', 'Manage Process Hours'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'select[name*="event"], select[name*="Event"]', value: '1' },
      { type: 'wait', ms: 800 },
      { type: 'hover', selector: 'td:has-text("Sign-In"), th:has-text("Sign-In")' },
      { type: 'wait', ms: 800 },
      { type: 'hover', selector: 'td:has-text("Sign-Out"), th:has-text("Sign-Out")' },
      { type: 'wait', ms: 800 },
    ],
    duration: 12000,
  },
  {
    module: 'manual_process_hours',
    slide: 4,
    label: 'Sign-In and Sign-Out buttons',
    menuPath: ['Payroll', 'Manage Process Hours'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'td a, table a' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Sign-In' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Sign-Out' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Approve Hours' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 14000,
  },
  {
    module: 'manual_process_hours',
    slide: 5,
    label: 'Autofill Sign-In and Sign-Out',
    menuPath: ['Payroll', 'Manage Process Hours'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Autofill Sign-In' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Autofill Sign-Out' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Approve Hours' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Back' },
      { type: 'wait', ms: 800 },
    ],
    duration: 14000,
  },

  // ── Billing ──────────────────────────────────────────────────────────────────
  {
    module: 'billing',
    slide: 4,
    label: 'Check Bill for Job',
    menuPath: ['Billing', 'Check Bill for Job'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'click', text: 'View Unbilled' },
      { type: 'wait', ms: 1500 },
      { type: 'hover', text: 'Hours Processed' },
      { type: 'wait', ms: 1000 },
    ],
    duration: 12000,
  },
  {
    module: 'billing',
    slide: 5,
    label: 'Manage Billing Process',
    menuPath: ['Billing', 'Manage Billing Process'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'select[name*="event"], select[name*="Event"]', value: '1' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'input[type="checkbox"]' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Get Invoice Data' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 16000,
  },
  {
    module: 'billing',
    slide: 6,
    label: 'Invoice Tabs',
    menuPath: ['Billing', 'Manage Billing Process'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Sign-In/Sign-Out' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Billing Tax' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Summary' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Billable Items' },
      { type: 'wait', ms: 800 },
      { type: 'click', text: 'Invoice Setup' },
      { type: 'wait', ms: 800 },
    ],
    duration: 16000,
  },
  {
    module: 'billing',
    slide: 7,
    label: 'Generate Invoice',
    menuPath: ['Billing', 'Manage Billing Process'],
    actions: [
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Generate Invoice' },
      { type: 'wait', ms: 1000 },
      { type: 'click', text: 'Summary' },
      { type: 'wait', ms: 1500 },
    ],
    duration: 12000,
  },
  {
    module: 'billing',
    slide: 8,
    label: 'Manage Contract',
    menuPath: ['Records', 'Manage Contract'],
    actions: [
      { type: 'wait', ms: 1200 },
      { type: 'fill', selector: 'input[placeholder*="client"], input[placeholder*="Client"], input[placeholder*="Search"]', value: 'Los Angeles' },
      { type: 'wait', ms: 600 },
      { type: 'click', text: 'Search' },
      { type: 'wait', ms: 1000 },
      { type: 'click', selector: 'td a, table a' },
      { type: 'wait', ms: 1000 },
      { type: 'hover', text: 'Rates' },
      { type: 'wait', ms: 800 },
    ],
    duration: 14000,
  },
];
